[package]
name = "reduce"
version = "0.1"
lean_version = "leanprover-community/lean:3.32.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "7500529f9836964b28bd6c317b0c76f33692505f"}
